# This is a basic workflow to help you get started with Actions

name: Deploy Azure Container Apps Environment

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: pwd
      run: pwd
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az account show
          az group create --name spinoza-cont-app-rg --location westeurope
          az deployment group create --resource-group spinoza-cont-app-rg --template-file infra/main.bicep \
             --parameters branchName='main' containerRegistryPassword= ${{secrets.ACR_PASSWORD}}  \
             cosmosDBConnectionString=${{secrets.COSMOSDB_CONNECTION_STRING}}

